[package]
name = "coinhunt"
version = "1.0.0"
edition = "2024"
license = "Apache-2.0"
publish = false
readme = "readme.md"

[dependencies.anyhow]
version = "1.0.100"

[dependencies.tokio]
version = "1.49.0"
features = ["full"]

[dependencies.fastrand]
version = "2.3.0"